Repository sveltejs/eslint-plugin-svelte, pull requests merged in 2022-07, with the labels that each got.

#165 perf: use esbuild-register as node loader to replace ts-node
  package.json
Labels: perf, internal

#167 chore: use prettier-plugin-pkg for consistent sorting
  .eslintrc.js
  package.json
Labels: internal

#202 Fix false positives for files other than `*.svelte` in `svelte/no-unused-svelte-ignore` rule
  src/rules/no-unused-svelte-ignore.ts
  tests/fixtures/rules/no-unused-svelte-ignore/valid/ignore-js-input.js
  tests/utils/utils.ts
Labels: bug
